name: SLSA Go Releaser (Linux only)
on:
    workflow_dispatch:
    release:
        types: [created]

permissions: read-all

jobs:
    build-linux:
        permissions:
            id-token: write # needed for signing
            contents: write # to upload release assets
            actions: read # to read the workflow path
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
        with:
            go-version: "1.23"
            config-file: .slsa-goreleaser.yml
